### ISSUE TITLE
Different stops with same name

### ISSUE THREAD

**Issue by kyawkhine** [vincent-paing/Yangon-Bus-Data#2]
အမှတ် ၁, ၁၄, ၂၆, ၂၇, ၄၂,(သင်္ဃန်းကျွန်း) နဲ့ အမှတ် ၄, ၅(ဒဂုံဆိပ်ကမ်း) ပြေးဆွဲတဲ့ ရတနာလမ်း မှတ်တိုင်ဟာ မတူပါဘူး မြို့နယ်ခွဲ ပြီးပြစေချင်ပါတယ်

**Comment by vincent-paing** [comment]
@kyawkhine ပြင်လိုက်ပါပြီ အစ်ကို၊ သေချာအောင် စစ်ပေးပါလား။ မှန်တယ်ဆိုရင်  close လိုက်တော့မယ်။

**Comment by kyawkhine** [comment]
ရပြီအကို
